# Site
repository: Tarun-msrit.github.io/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Tarun Ragothaman
title: Student
phone: 9448371659
email: tarun.ragothaman@gmail.com
# website: https://github.com/Tarun-msrit

# Social links
# twitter_username: facespics
github_username:  Tarun-msrit
# dribbble_username: jekyll
facebook_username: tarun.raghu.5
# flickr_username: jekyll
instagram_username: tarun__34
linkedin_username: tarun-raghu-848451194
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tarun and I'm a student studying in Ramaiah Institute of Technology in the department of <mark>Information Science</mark>. I am quite intersted in machine Learning and Mobile application development using Flutter. I also have a bit of experience in Django for making web apps. 
  Primary skills are: <mark>Machine Learning</mark><br>
                      <mark>Flutter Development</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
