# Site
repository: Tarun-msrit.github.io/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tarun Ragothaman
title: Student
phone: 9113282827
email: tarun.ragothaman@gmail.com
# website: https://github.com/Tarun-msrit

# Social links
# twitter_username: facespics
github_username:  Tarun-msrit
# dribbble_username: jekyll
facebook_username: tarun.raghu.5
# flickr_username: jekyll
instagram_username: tarun__34
linkedin_username: tarun-raghu-848451194
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, my name's Tarun and I'm a student studying in (3rd year, Ramaiah Institute of Technology, Bangalore) in the department of <mark>Information Science</mark>. I am quite intersted in machine Learning and Mobile application development using Flutter. I also have experience in working with Django Framework for making web applications. I'm quite proficient in python and java programming languages.<br><br> 
  Primary skills are : <mark>Machine Learning</mark> |
                      <mark>Flutter Development</mark>

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: My Interests and Skills
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in coding and software engineering some of my other interests and hobbies are:
   - Playing Tabla
   - Gaming
   - Playing Badminton

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
