# Site
repository: Tarun-msrit.github.io/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tarun Ragothaman
title: Student
phone: 9113282827
email: tarun.ragothaman@gmail.com
# website: https://github.com/Tarun-msrit

# Social links
# twitter_username: facespics
github_username:  Tarun-msrit
# dribbble_username: jekyll
facebook_username: tarun.raghu.5
# flickr_username: jekyll
instagram_username: tarun__34
linkedin_username: tarun-raghu-848451194
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, my name's Tarun and I'm a student studying in (3rd year, Ramaiah Institute of Technology, Bangalore) in the department of <mark>Information Science</mark>. I am quite intersted in machine Learning and Mobile application development using Flutter. I also have a bit of experience in Django for making web apps. I'm quite proficient in python and java programming languages.<br><br> 
  Primary skills are : <mark>Machine Learning</mark> |
                      <mark>Flutter Development</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: Education and Grades
- layout: left
  name: MS Ramaiah Institute of Technology
  dates: 2017 - 2021
  qualification: BE Information Science
#   quote: >
#     Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  description: | # this will include new lines to allow paragraphs
    During my time at MSRIT I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance. I have an aggregate <mark>CGPA</mark> of 7.76 throughout the duration of my course  in MSRIT.
    I spent a lot of my time working on different projects and was a member of the *National Service Scheme*.

- layout: left
  name: Deeksha Integrated PU college, Yelahanka
  dates: 2015 - 2017
  qualification: PUC - 12th
#   quote: >
#     Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  description: | # this will include new lines to allow paragraphs
    During my time at MSRIT I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance. I have an aggregate <mark>CGPA</mark> of 7.76 throughout the duration of my course  in MSRIT.
    I spent a lot of my time working on different projects and was a member of the *National Service Scheme*.

# More Section
more_title: My Interests and Skills
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in coding and software engineering some of my other interests and hobbies are:
   - Playing Tabla
   - Gaming
   - Playing Badminton

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
